<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 10,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 11,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 12,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2020-02-12 16:13:21',
                'updated_at' => '2020-02-12 16:13:21',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2020-02-12 16:13:22',
                'updated_at' => '2020-02-12 16:13:22',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 2,
                'title' => '仪表盘',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-12 16:26:12',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 2,
                'title' => '媒体管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-29 18:31:11',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => '用户管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-29 18:31:11',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => '权限管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-29 18:31:11',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => '工具',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-29 18:30:51',
                'route' => NULL,
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => '菜单管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-13 01:22:44',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => '数据库管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 2,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-13 01:22:44',
                'route' => 'voyager.database.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => '帮助信息',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 3,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-13 01:22:44',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 4,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-13 01:22:44',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 2,
                'title' => '插件',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 16,
                'order' => 6,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-13 01:22:44',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 2,
                'title' => '设置',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-02-12 16:26:12',
                'updated_at' => '2020-02-29 18:30:51',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Permissions',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2020-02-13 01:20:09',
                'updated_at' => '2020-02-13 01:20:09',
                'route' => 'voyager.permissions.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 2,
                'title' => '权限',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 5,
                'created_at' => '2020-02-13 01:20:47',
                'updated_at' => '2020-02-13 01:27:48',
                'route' => 'voyager.permissions.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2020-02-29 17:55:45',
                'updated_at' => '2020-02-29 17:55:45',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 29,
                'menu_id' => 2,
                'title' => '博客管理',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-02-29 18:20:33',
                'updated_at' => '2020-02-29 18:36:48',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 30,
                'menu_id' => 2,
                'title' => '文章',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 1,
                'created_at' => '2020-02-29 18:24:41',
                'updated_at' => '2020-02-29 18:27:10',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 33,
                'menu_id' => 2,
                'title' => '标签',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 4,
                'created_at' => '2020-02-29 18:33:59',
                'updated_at' => '2020-03-02 13:24:15',
                'route' => 'voyager.tags.index',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 34,
                'menu_id' => 2,
                'title' => '评论',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-chat',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 5,
                'created_at' => '2020-02-29 18:34:36',
                'updated_at' => '2020-02-29 18:37:05',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Tags',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2020-02-29 18:38:54',
                'updated_at' => '2020-02-29 18:38:54',
                'route' => 'voyager.tags.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Post Tags',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2020-03-02 12:53:46',
                'updated_at' => '2020-03-02 12:53:46',
                'route' => 'voyager.post-tags.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}