/* jshint esversion: 6 */

const types = {
    SET_USERNAME: "SET_USERNAME",

    SET_TAGS: "SET_TAGS",

    SHOW_SEARCH_DIALOG_VISIBLE: "SHOW_SEARCH_DIALOG_VISIBLE",
    HIDE_SEARCH_DIALOG_VISIBLE: "HIDE_SEARCH_DIALOG_VISIBLE",
    SET_SEARCH_DIALOG_VISIBLE: "SET_SEARCH_DIALOG_VISIBLE"
};

export default types;
